### ISSUE TITLE
Feature Request: Move "Now" to start of row

### ISSUE THREAD

**Issue by v4u6h4n** [amit9838/mousam#110]
Hey everyone :-)

Firstly, awesome application; I tried the KDE and Gnome weather apps, and this was the easy winner.

That said, I'm wondering if the `Now` block in the `Hourly`, `Wind` and `Precipitation` tabs could be moved to the front of the row of hours so I can see what the current wind/temp/precipitation is?

**Comment by georgescutelnicu** [comment]
Hello @amit9838 i'd like to implement this but first i'd like to know if you want this to be the default behaviour of the app or you want the users to be able to select either to use or not this feature from the preferences window.
![Screenshot_9](https://github.com/amit9838/mousam/assets/122637419/a1c7f810-ea1c-4ae6-a731-175814e977ed)


I'd also want to know, after displaying the current time at the front of the row, you'd like to continue the forecast for the next 23 hours (so would remain a 24 hours forecast) or the forecast should be displayed until the end of the current day (but it will look kinda weird i think).
![Screenshot_8](https://github.com/amit9838/mousam/assets/122637419/9ee0269f-c16a-48a4-b9c5-df3bf0d8136f)
![Screenshot_10](https://github.com/amit9838/mousam/assets/122637419/a7c81dfd-a0ca-47f2-b8c6-6e58c28384b8)

**Comment by v4u6h4n** [comment]
I think having an option in the settings is a good idea, the more control the better in my opinion. And it also makes sense to me that this be the default behaviour, as I think it will likely account for the majority of use cases.

Regarding your second question, I think only having the remaining hours of the current calendar day would render the feature a bit pointless when you get into the late hours of the day, having only one or two hours of forecast data visible, so the remaining 23 hours sounds good to me.

**Comment by amit9838** [comment]
> Hello @amit9838 i'd like to implement this but first i'd like to know if you want this to be the default behaviour of the app or you want the users to be able to select either to use or not this feature from the preferences window. ![Screenshot_9](https://private-user-images.githubusercontent.com/122637419/328035824-a1c7f810-ea1c-4ae6-a731-175814e977ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NzQ4MDQsIm5iZiI6MTcxNDk3NDUwNCwicGF0aCI6Ii8xMjI2Mzc0MTkvMzI4MDM1ODI0LWExYzdmODEwLWVhMWMtNGFlNi1hNzMxLTE3NTgxNGU5NzdlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQwNTQ4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYTY5YTVmMGYwY2E2Y2FjMjY0NDU4YTdmZDI0ZTE3YTNkMGFkMDhmNGI2YzFkMTI5MzkxYTBmNzRhMmE5OWY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dD-WWiBdSifQu0OfaOQ6omlB7LYu5Ofj6z4tHRvkj2c)
> 
> I'd also want to know, after displaying the current time at the front of the row, you'd like to continue the forecast for the next 23 hours (so would remain a 24 hours forecast) or the forecast should be displayed until the end of the current day (but it will look kinda weird i think). ![Screenshot_8](https://private-user-images.githubusercontent.com/122637419/328035830-9ee0269f-c16a-48a4-b9c5-df3bf0d8136f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NzQ4MDQsIm5iZiI6MTcxNDk3NDUwNCwicGF0aCI6Ii8xMjI2Mzc0MTkvMzI4MDM1ODMwLTllZTAyNjlmLWMxNmEtNDhhNC1iOWM1LWRmM2JmMGQ4MTM2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQwNTQ4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjdhOTk5ZmZjMTExYzZmMzgwNDU1ZWQ5M2FlODNjMDg5MzY4ODQyNzE1MTJjNWY1NzhlNDk4ZDA2YjFlOTU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NSkcQl7rkzviv_O3DyWvn3Z6cvhD3aMMv1c1NsAeGiM) ![Screenshot_10](https://private-user-images.githubusercontent.com/122637419/328035833-a7c81dfd-a0ca-47f2-b8c6-6e58c28384b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NzQ4MDQsIm5iZiI6MTcxNDk3NDUwNCwicGF0aCI6Ii8xMjI2Mzc0MTkvMzI4MDM1ODMzLWE3YzgxZGZkLWEwY2EtNDdmMi1iOGM2LTZlNThjMjgzODRiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNlQwNTQ4MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTI5NjY2ODExMDY2OWJlMzJjODNmZmRhMTUyMDJiYjdmNDFkNmRmZGNhMThlZWM2MTgyMGRjYzIzNjllNDQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YJtQDmek224B0BEk9Hdsyme-0Nn54VOS6e2WsiV_X30)
> 
> EDIT: Have some troubles reinstalling the app localy on win7 right now.

Hi @georgescutelnicu first of all thanks for working on this issue, 
Here is my thought i expect this feature,  pls correct me if you feel like,
- Don't strip off the data before now label (time) , because we want to show today's forecast for next 24hrs ( some times previous data is also important, anyways remaining hours are covered in tomorrow's forecast,
-  Just apply scroll offset such that it just shows two cards before now label (time) 
- I think here we don't need any option for this in setting , this adds extra logic in the code and i think this option is not useful in normal use case.
 (more: I'm also planning to remove `launch maximized` option form setting and save window size)

**Comment by georgescutelnicu** [comment]
Sounds good to me, just went through Gtk's docs and managed to make it look like this when you start the app:

![Screenshot_11](https://github.com/amit9838/mousam/assets/122637419/53f2a528-498b-4a89-910f-d3e4e2557b67)

I'll just take one more day to check it's behaviour when 'Now forecast' is at the start/end of the row, and also to check if everything i've done can be improved, even tho it's already looking pretty simple.

If you can confirm this is how u want it to look, would be great!

**Comment by v4u6h4n** [comment]
Thanks! :-)
