### ISSUE TITLE
Inconsistent Hourly Forecast Data for Today and Tomorrow

### ISSUE THREAD

**Issue by georgescutelnicu** [amit9838/mousam#111]
Hello,

I've noticed an inconsistency in the hourly forecast data retrieved for 'today' and 'tomorrow', the data seems to be the same regardless of location, so it can't be just a coincidence.

![issue](https://github.com/amit9838/mousam/assets/122637419/47ea62a8-3fcb-4b13-8ebf-aeb9e15fc71e)

Can someone take a look into it so i make sure is not only a me problem? I guess it might be related to how the weather items are added into the stack-box, since the `i` always starts from `0` we keep getting the today's forecast instead of tomorrow's one. 

**Note:** I'm running the app locally on Win7 OS, that's why im thinking it might be only me experiencing this issue and i decided to not look further into it for now.

**Comment by amit9838** [comment]
I'll look into it, thanks

**Comment by georgescutelnicu** [comment]
If you can confirm that this issue isn't isolated to my setup alone, i'll start working on a fix in the next few days.

**Comment by amit9838** [comment]
Sorry man for late response,
I don't think there is any issue, you can also test with other locations.

<img width="995" alt="SCR-20240503-rwdd" src="https://github.com/amit9838/mousam/assets/61614402/6f9db22b-1a6b-4735-a653-8983040ac78a">

**Comment by georgescutelnicu** [comment]
Look at my picture, consider 03:00 AM being the 0th index for today's forecast, and 12:00 am being the 0th index for tomorrow's forecast, they are the same, and so on until the 23rd index. So in your picture if u gonna check what's the today's 08:30 PM index in the today's forecast, u gonna see that index in the tomorrow's forecast has the same values. Let me get home and i'll edit my message to add some pictures with the entire today's and tomorrow's forecast.

**Comment by georgescutelnicu** [comment]
![ss1](https://github.com/amit9838/mousam/assets/122637419/02f583ae-ffbd-4359-b24d-e90753dcc5cd)
![ss2](https://github.com/amit9838/mousam/assets/122637419/427e7604-64dc-4c04-a169-4644df51bdc5)
![ss3](https://github.com/amit9838/mousam/assets/122637419/6a7aa0c1-9047-447c-ae2f-444ef595c6d2)


And so on until the end.

**Comment by amit9838** [comment]
Ok, let's simplify the testing, can you try with few more locations, 
Also one thing to note is , these timestamp is converted to your local time

**Comment by georgescutelnicu** [comment]
I know the timestamps are converted, and it doesn't matter at all because u don't retrieve the forecast by the timestamp, u are retriving them by index 0 to n. So there are 23 cards in todays forecast (starting from 0) and 23 in tomorrows forecast. Always the index 0 in todays is the same as index 0 in tomorrows, and so on until the last one, doesn't matter the location.

Even in the photos provided by you appear the same problem, check first 7 items of tomorrows with the first 7 of todays, they are the same.
![Screenshot_5](https://github.com/amit9838/mousam/assets/122637419/7a9b1ac6-20f8-4ea5-9572-dc5dc8f6b669)
![Screenshot_6](https://github.com/amit9838/mousam/assets/122637419/5aea51de-2dad-46b6-8c91-e0024e787de5)

**Comment by amit9838** [comment]
/fixed d69adf3548592c05f411ae4d189a1d8c556fda55

Thanks @georgescutelnicu  really i appreciate your effort in this issue, 🙂  

<img width="1001" alt="Screenshot 2024-05-04 at 11 05 31 PM" src="https://github.com/amit9838/mousam/assets/61614402/9f467f3c-b08d-4c22-ae10-a82cd6da4265">
