### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by amit9838** [amit9838/mousam#112]
add shortcuts for following events
- Refresh weather (ctrl+r)
- Open settings (ctrl + ,)
- Open locations dialog (ctrl + l)
- Press Enter to search when searching for locations (Enter)
If i'm missing something pls suggest 🙂

**Comment by francobattista** [comment]
Hi! Can i work on this?

**Comment by amit9838** [comment]
Sure, you can do it. 🙂

**Comment by francobattista** [comment]
I try to build the project, but i get this when i execute mousam:

Traceback (most recent call last):
  File "/home/franco/.local/share/mousam/mousam/main.py", line 48, in do_activate
    css_provider.load_from_data(css,len(css))
TypeError: Gtk.CssProvider.load_from_data() takes exactly 2 arguments (3 given)

**Comment by amit9838** [comment]
Is your build env configured properly?

![Screenshot_20240504-110258~2.png](https://github.com/amit9838/mousam/assets/61614402/0f6a25dc-15af-4335-acf8-662431120856)
Here you can see more info about the arguments 

https://lazka.github.io/pgi-docs/#Gtk-4.0/classes/CssProvider.html#Gtk.CssProvider

**Comment by Axel-Erfurt** [comment]
> I try to build the project, but i get this when i execute mousam:
> 
> Traceback (most recent call last): File "/home/franco/.local/share/mousam/mousam/main.py", line 48, in do_activate css_provider.load_from_data(css,len(css)) TypeError: Gtk.CssProvider.load_from_data() takes exactly 2 arguments (3 given)

I had the same problem and changed it to

```css_provider.load_from_data(css)```

Now it's working.

**Comment by amit-newstok** [comment]
Are you building with gnome builder?

**Comment by amit9838** [comment]
Are you building with gnome builder?
If not, 
Try to build with builder, it should ask for required dependencies on the first build.
