### ISSUE TITLE
New icon?

### ISSUE THREAD

**Issue by bertob** [amit9838/mousam#120]
Would you be interested in help with a new icon following the [HIG](https://developer.gnome.org/hig/guidelines/app-icons.html) more closely?

Here's a super quick attempt at just making the current icon use the square base shape, but I'd also be happy to try something more elaborate if you're interested.

![image](https://github.com/amit9838/mousam/assets/1908896/64feffd6-07c7-4afc-bd5d-ba9cce9a6fc4)

**Comment by amit9838** [comment]
Yes I'm ok with changing the icon. I'm not exactly clear about the design, but i would love something like the current icon with more elevated or isolated components. The border radius of the current icon(production version) is good.

**Comment by bertob** [comment]
Played around with it a bit more, and landed on this, which I quite like:

![image](https://github.com/amit9838/mousam/assets/1908896/ed780d39-1e45-4ef7-ba16-ebcca50de36f)

**Comment by amit9838** [comment]
> Played around with it a bit more, and landed on this, which I quite like:
> 
> ![image](https://private-user-images.githubusercontent.com/1908896/332769249-ed780d39-1e45-4ef7-ba16-ebcca50de36f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzODMxNDgsIm5iZiI6MTcxNjM4Mjg0OCwicGF0aCI6Ii8xOTA4ODk2LzMzMjc2OTI0OS1lZDc4MGQzOS0xZTQ1LTRlZjctYmExNi1lYmNjYTUwZGUzNmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjJUMTMwMDQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjZmNjZlNjJkZmU1OWY5YjdmZjE2MGM1YTFhNWE1MThkYjExZjYyZTc5OGRkMDdjODY0NWM5ODliNzkyMDFjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nrzKqkZ5kFoj-xQ_ASv6yZzBHj43oJnW6VqFTqP2w38)


- looks nice , Gradient on cloud and sun looks more natural, i can also see some elevation on the clouds, but looks like it is hard to see the elevation may be we can increase the intensity (not very sure),

- Also, i think it would be nice to go with with rounded square version, with same border radius as below.
<img width="141" alt="Screenshot 2024-05-22 at 6 31 15 PM" src="https://github.com/amit9838/mousam/assets/61614402/92c911be-1eb4-4d26-89c3-064506bcb7a3">

- May be we can also try with more variation in number of sun-rays.

> I'm not a designer, but for some reason i like the icons of these apps in gnome:  [G4Music, Monophony, bottles, Qbittorrent, Fractal, Decibels, Obsidian] , their color selection is too good 🙂.That's why they look, pleasant,
 What's your thought?

**Comment by bertob** [comment]
Tried some of your suggestions, how about this?

![image](https://github.com/amit9838/mousam/assets/1908896/1b862b30-b391-4bff-844f-e57d29b66938)

**Comment by amit9838** [comment]
Can you try with 4 sun rays?

**Comment by bertob** [comment]
![image](https://github.com/amit9838/mousam/assets/1908896/8047718e-aa4c-4825-a19e-7b8ea2a7b586)

**Comment by amit9838** [comment]
I'm not very sure man 😂. What's your thought?
I still feel like there is something missing. 
I leave this to you , I hope you'll come up with something this good. You can try anything like color design elements.
Thanks for your efforts 😊

**Comment by bertob** [comment]
Personally I still prefer the circular one, but really any of these would work nicely I think :)

**Comment by amit9838** [comment]
Ok so lets use the border radius of the production version in the last version you shared. Then we can use that.

**Comment by bertob** [comment]
Ok, here you go: 

![io github amit9838 mousam Source](https://github.com/amit9838/mousam/assets/1908896/7f6703fb-c280-4971-a04c-302c249ef184)

**Comment by amit9838** [comment]
Great , would be nice if you can also raise the pr with this icon 🙂.
