### ISSUE TITLE
Better app store listing

### ISSUE THREAD

**Issue by bertob** [amit9838/mousam#121]
This app looks great, there are only a handful of minor issues with the metadata to meet [Flathub's quality guidelines](https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines):

- The summary "Beautiful and lightweight weather app" is a bit too long (35 characters max). It'd also be better to phrase it as something active that people can do with the app, e.g. "Check the weather forecast".
- Screenshots should use default settings for window controls (close-only)
- Needs appstream brand colors ([Flathub guidelines](https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines/#brand-colors)). I'd be happy to help with this, but might be good to wait on #120 since icon and brand color need to fit together.

**Comment by amit9838** [comment]
That's nice feedback, Thanks. I'll look into it.

**Comment by amit9838** [comment]
Hi @bertob  I've changed the app description,  also updated the screenshots with default window controls.

**Comment by bertob** [comment]
This isn't quite fixed yet, mind reopening?

I've opened an MR for point 3, but there are still two other issues:

- The summary should use sentence case (e.g. 'Weather at a glance')
- The icon issue is still open, I'll follow up there :)

**Comment by amit9838** [comment]
Oh I'll fix that (2)
