### ISSUE TITLE
Automatically remember window size (width and height) and maximization state

### ISSUE THREAD

**Issue by nekohayo** [amit9838/mousam#129]
The width and height are always reset on startup, they should be remembered.

Likewise, I see you have a setting for "Launch Maximized"; that's unecessary I believe, you could just automatically save and restore that state too, independently from width and height (i.e. don't save the width/height while maximized).

See https://developer.gnome.org/documentation/tutorials/save-state.html

**Comment by amit9838** [comment]
Sure, that's already in my checklist 🙂.

**Comment by amit9838** [comment]
/fixed https://github.com/amit9838/mousam/commit/fa018d083b77cc7c6f84abd4c29e516a4199fe7f
