### ISSUE TITLE
Default window size too small

### ISSUE THREAD

**Issue by lightonflux** [amit9838/mousam#132]
The app does not remember its window size from the last start. So every time i start it the window is too small. 

![grafik](https://github.com/amit9838/mousam/assets/1377943/a5891e14-a59b-42cc-9173-0cdf60f30cb8)

**Comment by amit9838** [comment]
Duplicate  https://github.com/amit9838/mousam/issues/129

**Comment by amit9838** [comment]
/fixed https://github.com/amit9838/mousam/commit/fa018d083b77cc7c6f84abd4c29e516a4199fe7f
