### ISSUE TITLE
Some strings not translating in German

### ISSUE THREAD

**Issue by rainloreley** [amit9838/mousam#138]
There are some strings within the settings panel that are not being translated to German by the application, even though there is a translation available in [/po/de.po](https://github.com/amit9838/mousam/blob/master/po/de.po):
- "Time Format" + Description
- Title "Units & Measurements"
- Description of "°C"
- Description of "°F"
- Description of "Precipitation in inch"
- 
![grafik](https://github.com/amit9838/mousam/assets/28984823/eda29e50-ee27-4a54-9b23-fd30a3418ce6)

I tested around a bit and found that for the description of Fahrenheit the message ID is not the same as the text in the source code:
- Translation: https://github.com/amit9838/mousam/blob/96217e0add56990d1bfb11fd7545ec7f75a867ee/po/de.po#L647
- Source Code: https://github.com/amit9838/mousam/blob/96217e0add56990d1bfb11fd7545ec7f75a867ee/src/windowPreferences.py#L86

changing the message ID in `de.po` fixes it, but there's actually a typo in the message ID itself ("celcuis" -> "celsius") and I assume that fixing this typo is gonna mess up the translations to other languages as the ID is not the same anymore.
I have no idea how exactly these `.po` files work so I'm not even gonna try to fix it 🥲

**Comment by amit9838** [comment]
Oh that's strange , 
you can run below command to generate msgid with updated strings.
`xgettext --keyword=_ --keyword=N_ --keyword=C_:1c,2 --output=po/mousam.pot -f po/POTFILES`

**Comment by rainloreley** [comment]
I already tried that (I used the update-pot script but it's the same command), and from what I can see it mostly just updated the line numbers in `po/mousam.pot` (presumably because some code was added and the lines moved). other than that it's the same.

the issue seems to be that some `msgId`s in `de.po` don't match the ones in `mousam.pot`/the source code. changing the ids in `de.po` fixes the issue but there's a typo in the original (english) version and fixing that might screw up the other languages (because then the id doesn't match in these files)

**Comment by amit9838** [comment]
Can you pls let me know, the typo?

**Comment by rainloreley** [comment]
it's the one I mentioned in my original message:
https://github.com/amit9838/mousam/blob/96217e0add56990d1bfb11fd7545ec7f75a867ee/src/windowPreferences.py#L86
"celcuis" is spelled wrong, "celsius" would be correct

**Comment by amit9838** [comment]
ohk, got it, will fix this
