### ISSUE TITLE
Improve translation into Brazilian Portuguese

### ISSUE THREAD

**Issue by frankell** [amit9838/mousam#145]
I would like to ask for greater attention with the translation into Brazilian Portuguese. I can help with the translation.

In fact, we use 24h instead of AM PM and the Sunset time, even when chosen in the settings, still only shows in PM.

**Comment by amit9838** [comment]
that would be nice,  and for sunrise/sunset time,  we'll soon release a patch (1-2 days maybe)

**Comment by amit9838** [comment]
Hi @frankell I've updated the pot , you can translate now
