### ISSUE TITLE
ubuntu snap missing apparmor policy

### ISSUE THREAD

**Issue by delanthear** [amit9838/mousam#153]
I may be misunderstanding what's happening here, but you can't save out any configuration information due to missing a security profile.  Attempting to add a location causes this error:

`(mousam:5910): dconf-WARNING **: 22:22:16.581: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.74" (uid=1000 pid=5910 comm="python3 /snap/mousam/299/usr/bin/mousam" label="snap.mousam.mousam (enforce)") interface="ca.desrt.dconf.Writer" member="Change" error name="(unset)" requested_reply="0" destination="ca.desrt.dconf" (bus)`

Error on Xubuntu 24.04 Xfce, installed using Snap.

**Comment by delanthear** [comment]
Am having a bit of a crash course in app armor here.  When running Mousam is running, if I run an Apparmor_status, I see:

```
33 profiles are in enforce mode.
....
   snap-update-ns.mousam
...
   snap.mousam.mousam
...
16 processes are in enforce mode.
...
   /usr/bin/python3.10 (2690) snap.mousam.mousam
---
```

So, it does seem to have a policy there, it just appears the app is doing thing it's not allowed to in the policy (or my install is broken, which could well be possible as it's running on a Chromebook?)

**Comment by soumyaDghosh** [comment]
Hi @delanthear I am not 100% sure, but atleast 90% sure, that your installation is kind of broken. Can you share the output?

```bash
snap info mousam && snap version && snap connections mousam
```

**Comment by delanthear** [comment]
Sure!

```
snap info mousam && snap version && snap connections mousam
name:      mousam
summary:   Weather at a glance
publisher: Amit Chaudhary (amit0539)
store-url: https://snapcraft.io/mousam
contact:   amitchaudhary0539@outlook.com
license:   unset
description: |
  Current Weather conditions and forcasts.
  
  Features:
  
  - Displays real-time temperature, humidity, wind speed, UV index, pressure and more
  - Utilizes graphical representations, such as temperature , precipitation graphs and wind-speed
  with direction to provide an hourly forecast for the next 24 hours
  - Also provides tomorrow and 7-day forcasts
  - See conditions in metric or imperial systems
commands:
  - mousam
snap-id:      kxcnM5s6mkOkCKTUmolEeNtdIl0MWOJ3
tracking:     latest/stable
refresh-date: 2 days ago, at 22:21 BST
channels:
  latest/stable:    1.3.2 2024-07-01 (299) 921kB -
  latest/candidate: ↑                            
  latest/beta:      ↑                            
  latest/edge:      1.3.2 2024-07-10 (308)   5MB -
installed:          1.3.2            (299) 921kB -
snap    2.63
snapd   2.63
series  16
ubuntu  24.04
kernel  6.8.0-38-generic
Interface               Plug                   Slot                            Notes
content[gnome-42-2204]  mousam:gnome-42-2204   gnome-42-2204:gnome-42-2204     -
content[gtk-3-themes]   mousam:gtk-3-themes    gtk-common-themes:gtk-3-themes  -
content[icon-themes]    mousam:icon-themes     gtk-common-themes:icon-themes   -
content[sound-themes]   mousam:sound-themes    gtk-common-themes:sound-themes  -
dbus                    -                      mousam:mousam                   -
desktop                 mousam:desktop         :desktop                        -
desktop-legacy          mousam:desktop-legacy  :desktop-legacy                 -
gsettings               mousam:gsettings       :gsettings                      -
network                 mousam:network         :network                        -
opengl                  mousam:opengl          :opengl                         -
wayland                 mousam:wayland         :wayland                        -
x11                     mousam:x11             :x11                            -

```

**Comment by amit9838** [comment]
Sorry @delanthear for the late response, do you face  similar issue with any other app?

**Comment by amit9838** [comment]
Try removing everything,
`sudo snap remove --purge mousam`

Then install again.
Let's see if it works

**Comment by delanthear** [comment]
Hi,   Yeah a remove and reinstall still has the same problem.   I've discovered similar issues with a few other snaps so it looks like there is something wrong with Xubuntu 24.04 Xfce.   Sorry for the distraction!
