### ISSUE TITLE
Wind Direction Icon

### ISSUE THREAD

**Issue by jmm10134** [amit9838/mousam#159]
wind direction should point to the direction wind is from, like a weather vane.  I.e., you should rotate it 180 degrees.  Nice App :-)

**Comment by amit9838** [comment]
Can  you share some screenshots , because I can see it is correct for me

**Comment by jmm10134** [comment]
Hi Amit,By example here’s how Apple shows wind coming from east northeast:-JackOn Aug 20, 2024, at 9:20 AM, Amit Chaudhary ***@***.***> wrote:﻿
Can  you share some screenshots , because I can see it is correct for me

**Comment by amit9838** [comment]
<img width="531" alt="Screenshot 2024-08-23 at 7 43 50 AM" src="https://github.com/user-attachments/assets/b1a1a3e0-b24e-47fb-8d88-d2462585dec9">

This image is from apple weather,  if it says wind is coming from east then then arrow points towards west.

**Comment by jmm10134** [comment]
Nice!-JackOn Aug 22, 2024, at 9:17 PM, Amit Chaudhary ***@***.***> wrote:﻿
Screenshot.2024-08-23.at.7.43.50.AM.png (view on web)
This image is from apple weather,  if it says wind is coming from east then then arrow points towards west.
