### ISSUE TITLE
Day Max displayed appears based on WEEKLY max

### ISSUE THREAD

**Issue by LNDbx** [amit9838/mousam#180]
The section labeled "Day Max" supposedly means to displays the daily maximum temperature. However, the variable de facto displays the WEEKLY maximum temperature, rather than the daily maximum temperature as expected.

**Feature Request:**
While this seems to be an undesirable bug, it could be leveraged for an augmented feature, i.e. to display both daily **as well as** weekly expected maximums co-located.

**Comment by amit9838** [comment]
I hope version 1.4.0 fixes the issue.

**Comment by LNDbx** [comment]
Can confirm, this appears to be fixed. Thank you immensely for your hard work, really enjoying mousam.
