### ISSUE TITLE
Update the website

### ISSUE THREAD

**Issue by amit9838** [amit9838/mousam#36]
### Pages
- Home
- Downloads (Installation)
- About

#### Home 
- Title 
- Description
- Screenshots
- Features
- Download Now (link to download page)
- Footer

#### Downloads
- provide some info about the current version just above the download links and add link to 
github downloads (button with text  "download from github").
- Platform 
- link to platform (like flatpak link)
- CLI installation instructions (like -  flatpak install flathub io.github.amit9838.weather,  and RUN command)

#### About
- Project card
- Contributors card (with social links)

##### Prefer dark mode (would be great with theme toggle option)

> Design idea is appreciated

**Comment by AYehia0** [comment]
Hello @amit9838 , I have created a simple page, checkout this branch : https://github.com/AYehia0/weather/tree/gh-pages
but I don't know how to merge lol. I couldn't merge due to different histories.

check it out here : https://ayehia0.info/weather/

**Comment by amit9838** [comment]
Thank you for your contribution @AYehia0, Website looks great, we'll handle merge issues 🙂 
Let's  make few changes here:
1. create header and move the menu links in the header and also include link of the github repo.
2. Isolate the sections into pages (like downloads page, about page)
3. If possible can you add option to toggle theme ( toggle btn in header) otherwise make the whole website dark(apple's dark color palette).
4. let's not align everything center.
5. on the downloads  page provide some info about the current version just above the download links and add link to 
github downloads (button with text  "download from github").
7. Let's highlight code snippet in the download section,  just like readme.
8. Add project card in the about section with information like ( number of stars, forks etc may be also include downloads, number of contributors)
9.  If possible also create contributors card.

**Comment by amit9838** [comment]
Hi @AYehia0 just released new version , hopefully you are able to raise the pr now

**Comment by amit9838** [comment]
I've modefied your website little bit and deployed it on gh-pages you can see from here [link](https://amit9838.github.io/weather/)
