### ISSUE TITLE
Gathering Weather Data Spinner too big

### ISSUE THREAD

**Issue by brielov** [amit9838/mousam#41]
Seems like the loading spinner is ginormous when the window is maximized. Don't really know if this is a feature or a bug in which case, feel free to close the this issue (if its a feature).

![image](https://github.com/amit9838/weather/assets/42145089/b406dfe0-e128-4d6b-9e4b-f14459eae4c3)

**Comment by amit9838** [comment]
not a feature actually 😆, will fix it

**Comment by amit9838** [comment]
#54
