### ISSUE TITLE
Precipitation is always shown in mm

### ISSUE THREAD

**Issue by kmoad** [amit9838/mousam#51]
The amount of precipitation is being shown in mm, even though I have my units set to imperial.

![Screenshot from 2024-01-19 01-12-04](https://github.com/amit9838/weather/assets/19417207/5f881483-7af0-4d71-8eeb-f4bdbacda2e0)

**Comment by amit9838** [comment]
https://github.com/amit9838/mousam/commit/ccebfadc8cfa63c76accec6f63b67c34fdd1e653
