### ISSUE TITLE
App overflows on low resolution displays

### ISSUE THREAD

**Issue by raghavdhingra24** [amit9838/mousam#52]
Hi there,
The minimum size of the app is causing it to overflow my display which has a resolution of 1366x768px.
[Video Showing the Same](https://github.com/amit9838/weather/assets/106472154/495c0949-c13a-4fd5-be71-e0f13bb1bae3)

App version = 1.0.1 from snap-store
OS - Ubuntu 23.10
DE - Gnome 45.2

**Comment by raghavdhingra24** [comment]
A suggestion could to add a scrollbar to allow scrolling of content.

**Comment by hsbasu** [comment]
> A suggestion could be to add a scrollbar to allow scrolling of content.
> 
> Edit - Grammar

Yes. This is the solution. I think I can do it.

**Comment by raghavdhingra24** [comment]
Hi @amit9838, have you pushed this on `snap-store` as I am still facing the issue. I am on `latest/edge` channel

**Comment by amit9838** [comment]
No this change will take effect from the next version

**Comment by raghavdhingra24** [comment]
I have updated the app to version 1.1.0. Now the condition is a little better but still some content is cut.

[Screencast from 2024-02-25 11-50-35.webm](https://github.com/amit9838/mousam/assets/106472154/e1ba4b85-462c-47ff-aa84-6eeb4447236d)

**Comment by amit9838** [comment]
O , will try scrollable behaviour.

**Comment by raghavdhingra24** [comment]
Thanks, this issue is now fixed and can be closed.
