### ISSUE TITLE
The visibility is always 24.1 km

### ISSUE THREAD

**Issue by wuqso** [amit9838/mousam#55]
As the title shows, the visibility is always 24.1 km for different days and different cities in version 1.0.1. What's more, the air pollution information is renewed slowly, lagging the actuality, in fact.

- [ ] Fix Visibility
- [x] Fix Air Pollution

**Comment by hsbasu** [comment]
I am using the flatpak of mausam, but I am also reproducing the same except for for the location **Bagnan**. See attached Screenshot.
![Screenshot from 2024-02-01 12-01-00](https://github.com/amit9838/weather/assets/41947504/aac0a4e5-3d01-4fb9-b0c8-916604199463)

**Comment by amit9838** [comment]
I thnink there is some issue with the api data, will check for alternatives sources for this.

**Comment by amit9838** [comment]
Fixed air pollution https://github.com/amit9838/mousam/commit/b06338f1da1f4df91ddbf562cd3faa3e7a6065a6

**Comment by wuqso** [comment]
The visibilities of Beijing and Wuhan are still 24.1 km in Mousam.

**Comment by amit9838** [comment]
I have fixed the air pollution delay , but these is something wrong with visibility data, so i need to check for alternatives.
