### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by hsbasu** [amit9838/mousam#56]
Hi,
I really liked this app. Especially it provides some quite accurate forecasts at par with the weather channel.
I have implemented debian packaging for this app. If you are interested I can create a PR. You can check out [this branch](https://github.com/hsbasu/weather/tree/deb-packaging).

**Comment by hsbasu** [comment]
@amit9838 I would also like to have your opinion on this issue as well.

**Comment by amit9838** [comment]
Yes, can go with this once we make consistent app id in flatpak and snap
