### ISSUE TITLE
Inconsistent naming convention

### ISSUE THREAD

**Issue by hsbasu** [amit9838/mousam#57]
I observed at some places the program is named as **weather**, while some other places use **mousam** as the package name as in **snap**. I'd suggest sticking to a single naming convention with **mousam**.

For example, you need to rename the following files and their contents as:
```
io.github.amit9838.weather.json  -->  io.github.amit9838.mousam.json
```
and its contents where ever you used `weather`.

**Comment by hsbasu** [comment]
Do you want me to create a PR?

**Comment by amit9838** [comment]
sure that would be great

**Comment by hsbasu** [comment]
> sure that would be great
> 

Should I use **mousam**?

**Comment by amit9838** [comment]
yes mousam

**Comment by hsbasu** [comment]
Hi! @amit9838 I made necessary modifications for renaming. I just want to confirm are you willing to rename the github repo to mosam?

**Comment by amit9838** [comment]
Yes I'm okay to change the name, I need to check whether we can modify the app id so that  app can be identified ok flatstore

**Comment by hsbasu** [comment]
I guess you'd need to register the dbus name again.

**Comment by amit9838** [comment]
Can you share the steps?

**Comment by hsbasu** [comment]
To create a snap on your system you need to run `snapcraft` from the repo directory, better with the option `snapcraft --verbose`. It'll create **mousam_version.snap** in the repo directory.

**Comment by amit9838** [comment]
yes snap is using app id as mausom, i'm more concerned about flatpak

**Comment by hsbasu** [comment]
I'm sorry. I never built a flatpak. But while building snap for one of my apps, I needed to get the dbus name(in this case **io.github.amit9838.mousam**) approved from snap moderators. Only then I was able to publish on snap store. For flatpak, I think the process is same.

**Comment by amit9838** [comment]
i didn't found any valid documentation about changing the app id, i think we will have to republish the app on flathub, and i don't found any proof that it will retain old data on app store (or flathub)

**Comment by hsbasu** [comment]
I'm Testing flatpak now. Let's see if it builds or not.

**Comment by amit9838** [comment]
> Hi! @amit9838 I made necessary modifications for renaming. I just want to confirm are you willing to rename the github repo to mosam?
> 
> If you are not, I'd need to undo some these modifications.

So lets revert the changes for now, we can change it in future if we find any valid doc

**Comment by hsbasu** [comment]
> > Hi! @amit9838 I made necessary modifications for renaming. I just want to confirm are you willing to rename the github repo to mosam?
> > If you are not, I'd need to undo some these modifications.
> 
> So lets revert the changes for now, we can rename it in future in case we find any valid doc

I don't see any issue in renaming. Please check [this](https://docs.flathub.org/docs/for-app-authors/maintenance/#end-of-life). Here they support renaming flatpak to a new app id.

**Comment by amit9838** [comment]
Seems like it should work, will try this, thanks.

**Comment by hsbasu** [comment]
Actually there is another way of doing this. Simply rename https://github.com/flathub/io.github.amit9838.weather to https://github.com/flathub/io.github.amit9838.mousam if you have rename access. then
1. replace [this file](https://github.com/flathub/io.github.amit9838.weather/blob/master/io.github.amit9838.weather.json)

**Comment by amit9838** [comment]
Can you share the source where you got this?

**Comment by hsbasu** [comment]
> Can you share the source where you got this?
> I can't rename the repo actually 

In that case it's best to use the first option.

**Comment by amit9838** [comment]
I just tested by changing the app id and few required file, it dosen't seem like the app is going to build this way, 
So, As far as i can understand that what they are saying is, we can release a new app with app id `io.github.amit9838.mousam`.  and we can add flathub file saying `end-of-cyclc` and add new app id so that user can switch to the new new app when they are prompted to switch.

**Comment by hsbasu** [comment]
Yes. You're right. I pushed changes to a branch on my repo. But have not created the PR. You can test it.

**Comment by hsbasu** [comment]
@amit9838 I am seeing many merge commits in the commit history which are unnecessary and looks ugly. I would suggest using the **squash and merge** option when merging a PR with a single commit. If there are multiple commits in a PR, you should use **Rebase and merge** option. This keeps the commit history linear and clean.
