### ISSUE TITLE
Wrong version in About window

### ISSUE THREAD

**Issue by hsbasu** [amit9838/mousam#78]
Please check the screenshot.
![Screenshot from 2024-02-12 21-40-29](https://github.com/amit9838/mousam/assets/41947504/cb38c8cd-5b1d-4778-af56-3b7ae5f795d3)

All packaging methods: snap, flatpak and deb showing same error.

**Comment by amit9838** [comment]
Actually I forgot to update the version number here. BTW the latest version is 1.0.2
