### ISSUE TITLE
State "No Internet" when external DNS communication blocked

### ISSUE THREAD

**Issue by RoepLuke** [amit9838/mousam#84]
Hey, I really like the design of your App, but was unable to use it as I always had the state "no internet".
I couldn't understand why only this Flatpak App couldn't access the internet.

**The App has the flatpak sandbox network permission, so that shouldn't be the problem.**
![grafik](https://github.com/amit9838/mousam/assets/29387023/4e0f5317-a2b1-49ea-883a-22a98f645716)

**I then used Wireshark to try to find the issue and stumbled upon this. A connection to 1.1.1.1 on Port 53 (DNS) is blocked by my network gateway. This is intended as I have a local resolver and don't want other DNS Servers to be used on the network.**
![Bildschirmfoto vom 2024-02-12 22-40-39](https://github.com/amit9838/mousam/assets/29387023/7f614b09-6f25-4f63-b274-7e88b7f53086)
![Bildschirmfoto vom 2024-02-12 22-41-10](https://github.com/amit9838/mousam/assets/29387023/59b55da7-651d-4f4b-bed3-e7dee5b46962)

**The allowed DNS Server is set as the system / network connection DNS Server. It seems the App has 1.1.1.1 hard-coded and therefore ignores the system-wide DNS setting.**
![Bildschirmfoto vom 2024-02-12 22-56-50](https://github.com/amit9838/mousam/assets/29387023/ed3084ce-d6a2-4d83-9392-1e72d0a31792)

When I temporarily disabled the external DNS filter on my network gateway, the application worked normally.

As far as I can see, the App should just use the system-wide DNS setting, like any other Application does.
It could also be that the App uses a DNS Request to 1.1.1.1 to perform the internet connectivity check itself, then maybe using `ping one.one.one.one` or `nmcli networking connectivity` (on Devices using NetworkManager) instead would be less error-prone.

See [here](https://www.networkmanager.dev/docs/api/latest/nmcli.html) under "Networking Control Commands" for the possible return values of `nmcli networking connectivity`.

Thank you very much!

**Comment by RoepLuke** [comment]
Would be willing to donate let say 15,00 € (about 1300 INR) if this could be done.

**Also your KoFi Link is broken...**
![grafik](https://github.com/amit9838/mousam/assets/29387023/ae0c8798-2188-4793-844f-f2a3685a7d23)

**Comment by amit9838** [comment]
Thanks for reporting the issue, Now I have added various fallbacks to check internet 🙂, Can you confirm if this package works for you

**Comment by amit9838** [comment]
> Would be willing to donate let say 15,00 € (about 1300 INR) if this could be done.
> 
> **Also your KoFi Link is broken...** ![grafik](https://private-user-images.githubusercontent.com/29387023/304245197-ae0c8798-2188-4793-844f-f2a3685a7d23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MDcwMjAsIm5iZiI6MTcwNzgwNjcyMCwicGF0aCI6Ii8yOTM4NzAyMy8zMDQyNDUxOTctYWUwYzg3OTgtMjE4OC00NzkzLTg0NGYtZjJhMzY4NWE3ZDIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDA2NDUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiZjllNTUwNmNlMmUwZGUyNTA5YzhmMWQ2N2JmNjM3MzBlMzY1MzYwYzVkZjU2YmMzMTliYzdkNWZhMDhjZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c9ZI_TgOTj57H8Je__MNkpK8-GQarXhAdHzprM24auI)

Will appreciate you contribution,  fixed the link thankyou

**Comment by RoepLuke** [comment]
Can confirm that it now works. This dev Version lags heavily on my machine, but I'll assume that's because it's not made for release.

Logs the following when started:
```
Internet conncetion confirmed through:  http://www.google.com
amdgpu_device_initialize: amdgpu_query_info(ACCEL_WORKING) failed (-25)
amdgpu: amdgpu_device_initialize failed.
libEGL warning: egl: failed to create dri2 screen
amdgpu_device_initialize: amdgpu_query_info(ACCEL_WORKING) failed (-25)
radv/amdgpu: failed to initialize device.
MESA: error: ZINK: vkEnumeratePhysicalDevices failed (VK_ERROR_INITIALIZATION_FAILED)
MESA: error: ZINK: failed to choose pdev
libEGL warning: egl: failed to create dri2 screen
```

Would be nice if `nmcli networking connectivity` could be used as a primary source for verifying connection (if available) as [then distributions and possibly users can define the Method and URL themselves](https://www.networkmanager.dev/docs/api/latest/NetworkManager.conf.html#id-1.2.3.13), but at the end of the day that is up to you as the dev.

Donated the promised amount via buymeacoffee.

**Comment by amit9838** [comment]
Thanks for you confirmation .
Yes, producton version will work fine,
will definetly check , wheter we can use `nmcli networking connectivity`
Thankyou very much for your contribution.
