### ISSUE TITLE
No Title bar in the panel.

### ISSUE THREAD

**Issue by Growebis** [amit9838/mousam#90]
Currently the app has no title bar as shown in the picture below:
![image](https://github.com/amit9838/mousam/assets/113867283/6f8fde4c-b215-4983-900b-c777ddd4c6fa)
Not sure why but maybe because the app name was not set in the title bar?

**Comment by amit9838** [comment]
Hey @Growebis  what extension are you using?

**Comment by Growebis** [comment]
> Hey @Growebis which extension are you using?

![image](https://github.com/amit9838/mousam/assets/113867283/79bcf878-e9f9-4325-ac6b-da29fcef7eb1)

Also i think i know why, for grouped window list i set the button label to window title and not application name

Window title
![image](https://github.com/amit9838/mousam/assets/113867283/36e1e2f6-f5e3-4ceb-b16e-c8fef6902867)
Application name
![image](https://github.com/amit9838/mousam/assets/113867283/a90233a9-7c33-447c-8899-5f10b228717f)
Forgot to say this but im running Linux Mint 21.2 Cinammon

**Comment by amit9838** [comment]
<img width="624" alt="Screenshot 2024-02-20 at 9 22 39 AM" src="https://github.com/amit9838/mousam/assets/61614402/1c596199-a1cb-467d-be0e-64f5e40c8d9b">

Ok, Actually it was intentional to not put the title there because, branding was not looking that good in the top cernter of the app.

**Comment by Growebis** [comment]
> 
> Ok, Actually it was intentional to not put the title there because, branding was not looking that good in the top cernter of the app.

Is it possible to somehow add the title but not show it in the app? (sorry for not responding sooner)

**Comment by amit9838** [comment]
I coudn't found any such methods in gtk , So it is not posstibe for now atleast.
