### ISSUE TITLE
Wrong description in flathub

### ISSUE THREAD

**Issue by Blakyrin** [amit9838/mousam#92]
WIth the new name, the flathub page received a new issue, the word weather got replaced with the word mousam in "Beautiful and lightweight weather app", to "Beautiful and lightweight mousam app"
![imagen](https://github.com/amit9838/mousam/assets/111029746/db70c4c3-8968-43b4-9cf1-e1d6fdb11af2)

**Comment by amit9838** [comment]
fixed
