### ISSUE TITLE
[Suggestion] Add 24h time

### ISSUE THREAD

**Issue by McBaumwolle** [amit9838/mousam#93]
Love the app, but would be nice to have the option to toggle between 12h and 24h time style. 

![image](https://github.com/amit9838/mousam/assets/67203883/ae69332e-553d-4f35-85a5-6d5b9a090dd4)

Thanks!

**Comment by amartyadav** [comment]
Hi @amit9838, I want to implement this. Starting development on this right now. Cheers.

**Comment by amit9838** [comment]
Wow, that's great 🙂

**Comment by amit9838** [comment]
Hi, @amartyadav just wanted to know , are you working on this or do i do this?

**Comment by nekohayo** [comment]
It would be best to just get that information from the system settings; GNOME exposes something for this in the GNOME Control Center UI, so it's available as a desktop settings  schema etc. I don't know about other DEs, but at least in GNOME this could be inherited.

**Comment by panyann** [comment]
At the moment with 12 hours system you can't even say if it shows a day or night, because it doesn't display AM and PM 😅

**Comment by amit9838** [comment]
/fixed https://github.com/amit9838/mousam/commit/b10a8dd128818d21a37d46b09738a39c3c2863be

**Comment by forteller** [comment]
Hi. Thanks for a really nice app! I came here to ask for the same as @nekohayo: Would it be possible to take the info on clock (and other measurements) from the system settings?
