### ISSUE TITLE
[Suggestion] Wind speed

### ISSUE THREAD

**Issue by Maraniro122** [amit9838/mousam#96]
Add optional wind speed values in m/s and miles/hour

**Comment by amit9838** [comment]
there is already **metric and imperial** systems

**Comment by Strit** [comment]
The problem is that if we select metric system it measures in km/h, which is rare when measuring wind speeds. Most weather institutes measure it in meters/second in metric system.

**Comment by LukaszH77** [comment]
Meters/second mean nothing to me. I need km/h to know how hard will it be to cycle that day :)
